# TODO: Somehow carry-over the build from PR's? Only deploy if docs have actually changed?

name: Deploy docs site to GH Pages

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    name: Build docs site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/setup-packages
        with:
          node-version: 20

      - name: Build package type definitions
        run: pnpm run --filter "./packages/**" build:types

      - name: Generate docs markdown
        run: pnpm run --filter "docs-site" docs:gen

      - name: Build docusaurus site
        run: pnpm run --filter "docs-site" build

      - name: Upload build artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-site/build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy to GH Pages
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
